### ISSUE TITLE
Add a kebab button to the appbar

### ISSUE THREAD

**Issue by TugbaDalmaz** [devonfw-sample/basic-flutter#22]
**Description**
As a user, I'd like to have a kebab button in the appbar of the employee list page which contains several options.

**Functions of the kebab button**
- Delete (should allow multi-select of the entries of the employee list in order to delete more than one employee at once)
- Grid layout (should change the view of the employee list from a list view into a grid view which involves displaying each 2 employees beside each other)
- If the grid layout is set then you should have the possibility to switch back to the list view

**Acceptance Criteria**
- The delete button shall be greyed out and not usable or clickable if there are no more employee entries in the list (all employees were deleted) or the retrieved list from the server is simply empty

**Developer Hints**
- This is the icon that you need to use [Flaticon](https://www.flaticon.com/premium-icon/dots_2311524?term=dots&page=1&position=1&page=1&position=1&related_id=2311524&origin=search)

**Comment by HKayed** [comment]
Functions of the kebab button were divided into smaller tickets for simplicity
